name: "2 - Build"

on: 
  push:
    paths:
      - src/**
      - .github/workflows/**
    branches:
      - main

jobs:
  node-version-test:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up nodejs version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package
      run: npm install
    - name: Test
      run: npm test
  erbium-alpine-test:
    needs: node-version-test
    runs-on: ubuntu-latest
    container:
      image: node:erbium-alpine
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install package
      run: npm install
    - name: Test
      run: npm test
  build-image:
    needs: erbium-alpine-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: build container image
      run: docker build -t richiebono/nestjs-rest-cqrs-pattern:${{ github.sha }} .
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push container image
      run: docker push richiebono/nestjs-rest-cqrs-pattern:${{ github.sha }}
